// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.shekhar.todo.domain;

import java.util.Date;

public class TodoItemBuilder extends TodoItemBuilderBase<TodoItemBuilder> {
	public static TodoItemBuilder todoItem() {
		return new TodoItemBuilder();
	}

	public TodoItemBuilder() {
		super(new TodoItem());
	}

	public TodoItem build() {
		return getInstance();
	}
}

class TodoItemBuilderBase<GeneratorT extends TodoItemBuilderBase<GeneratorT>> {
	private TodoItem instance;

	protected TodoItemBuilderBase(TodoItem aInstance) {
		instance = aInstance;
	}

	protected TodoItem getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTask(String aValue) {
		instance.setTask(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDueOn(Date aValue) {
		instance.setDueOn(aValue);

		return (GeneratorT) this;
	}
}
