// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.shekhar.todo.domain;

import java.util.ArrayList;
import java.util.List;

public class UserBuilder extends UserBuilderBase<UserBuilder> {
	public static UserBuilder user() {
		return new UserBuilder();
	}

	public UserBuilder() {
		super(new User());
	}

	public User build() {
		return getInstance();
	}
}

class UserBuilderBase<GeneratorT extends UserBuilderBase<GeneratorT>> {
	private User instance;

	protected UserBuilderBase(User aInstance) {
		instance = aInstance;
	}

	protected User getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPassword(String aValue) {
		instance.setPassword(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTodoLists(List<TodoList> aValue) {
		instance.setTodoLists(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedTodoList(TodoList aValue) {
		if (instance.getTodoLists() == null) {
			instance.setTodoLists(new ArrayList<TodoList>());
		}

		((ArrayList<TodoList>) instance.getTodoLists()).add(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withHobbies(List<String> aValue) {
		instance.setHobbies(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedHobby(String aValue) {
		if (instance.getHobbies() == null) {
			instance.setHobbies(new ArrayList<String>());
		}

		((ArrayList<String>) instance.getHobbies()).add(aValue);

		return (GeneratorT) this;
	}
}
